#!/bin/sh

APP_NAME=`echo ${MARATHON_APP_ID}|cut -d'/' -f3`
if [ -z ${APP_NAME} ]; then
    APP_NAME=unknown_marathon_app
fi

sed -i 's,\(Host \)<HOSTNAME>,\1"'$APP_NAME'",' /etc/collectd/conf.d/jmx.conf
