#!/bin/sh
sleep 10 # need collectd to start after other processes
# chpst (runs a program with changed process state) memory limit 192mb
exec chpst -m 201326592 /usr/sbin/collectd -C /etc/collectd/collectd.conf -f >/dev/null
