#!/usr/bin/env bash
set -ex

if [ $DOCKER_TAG != "latest" ]; then
    MINOR_VERSION=$(echo $DOCKER_TAG | cut -d "." -f 1-2)

    RUBY_VERSION=$(docker run --entrypoint ruby-version.rb $IMAGE_NAME)

    docker tag $IMAGE_NAME $DOCKER_REPO:$RUBY_VERSION
    docker push $DOCKER_REPO:$RUBY_VERSION
else 
    echo "Not retagging latest."
fi

