#!/bin/bash
#
# This script is intended to be sourced into a ship file to set the IP
# of the gateway or host.

if [ -z "$DOCKERHOST" ] && [ -n "$DOCKERHOST_API" ]; then
  # Get the dockerhost from an API
  DOCKERHOST=`curl -s --fail $DOCKERHOST_API 2>/dev/null`
fi

if [ -z "$DOCKERHOST" ]; then
  # Use the default gateway as the dockerhost
  DOCKERHOST=`netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}'`
fi

(grep dockerhost /etc/hosts > /dev/null) || \
(echo "$DOCKERHOST dockerhost" >> /etc/hosts)

export DOCKERHOST
