#!/bin/bash

docker_for_mac=$(dig +short docker.for.mac.localhost)
if [ "${docker_for_mac}" != "" ]; then
  # docker for mac is weird, so point to "special" docker for mac endpoint
  echo "${docker_for_mac}    local.dev.socrata.net" >> /etc/hosts
else
  # running directly on docker from a unix host, point at bridge IP
  echo "172.17.0.1    local.dev.socrata.net" >> /etc/hosts
fi
