#!/bin/bash
#
# This script servces as a flexible docker ENTRYPOINT
# - Add a script to /etc/ship.d/run to be the default execution
# - Other scripts in /etc/ship.d/ can be specified as the docker command
# - Any executable (absolute or on PATH) can also be specified as the command
# - Adds a standard way of getting the docker host IP

set -e

COMMAND=${1:-run}
shift || true

source /bin/set_ark_host # in /etc/hosts
source /bin/set_ark_hostname

if [ -d /etc/pre-init.d ]; then
    run-parts -v --exit-on-error /etc/pre-init.d
fi

if [ -e /etc/ship.d/$COMMAND ]; then
  /etc/ship.d/$COMMAND $@
else
  command -v $COMMAND >/dev/null 2>&1 || {
      echo >&2 "Aborting. Not a valid command: $COMMAND"; exit 1;
  }
  $COMMAND $@
fi

