#!/bin/bash
#
# This script servces as a flexible docker ENTRYPOINT
# Add a script to /etc/start.d/run to be the default execution
# Other scripts in /etc/start.d/ can be specified as the docker command
# Any executable (absolute or on PATH) can also be specified as the command

set -eo pipefail

COMMAND=${1:-run}
shift || true

if [ -e /root/$COMMAND ]; then
  /etc/start.d/$COMMAND $@
else
  command -v $COMMAND >/dev/null 2>&1 || { echo >&2 "Aborting. Not a valid command: $COMMAND"; exit 1; }
  $COMMAND $@
fi

