#!/usr/bin/env bash
#
# This script is intended to be sourced into a ship file to set the IP
# of the gateway or host.
case $ARK_HOSTNAME in
  aws-private)
    ARK_HOSTNAME=`curl -s --fail http://169.254.169.254/latest/meta-data/local-hostname 2>/dev/null`
    ;;
  aws-public)
    ARK_HOSTNAME=`curl -s --fail http://169.254.169.254/latest/meta-data/public-hostname 2>/dev/null`
    ;;
esac

if [ -z "$ARK_HOSTNAME" ]; then
  # Use the default gateway to base the hostname on
  ARK_HOSTNAME=ark-host
fi
export ARK_HOSTNAME
