#!/bin/sh
if [ -z $CHRONOS_MAIL_SERVER ] && [ ! -z $ARK_HOST ]; then
  export CHRONOS_MAIL_SERVER=$ARK_HOST:25
fi
if [ -z $CHRONOS_HOSTNAME ] && [ ! -z $ARK_HOST ]; then
  export CHRONOS_HOSTNAME=$ARK_HOST
fi
exec su socrata -c '/usr/bin/chronos --no-logger'
